# Site
repository: ryesakurano/ryesakurano.github.io
favicon: fas fa-cat

# Content configuration version
version: 2

# Personal info
name: Lingjun Xu (许灵筠)
# title: 
email: xlj_rk[at]pku.edu.cn
# website: www.github.com/RyeSakurano

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  RyeSakurano
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: 灵筠-许-99a2891a2
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Scarlet Rook (blog)
  icon: fas fa-book-open
  url: https://ScarletRook.github.io
- title: PKU EECS 129
  icon: fas fa-headphones
  url: https://eecs129.site
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
# about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm currently a graduate student at [Key Laboratory of Machine Perception, Ministry of Education](http://www.cis.pku.edu.cn/index.htm), [Peking University](https://pku.edu.cn).

  Please contact me via xlj_rk[at]pku.edu.cn or lingjunxu.rk[at]outlook.com.
#  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>




content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Guangzhou Zhixin High School
        caption: 2014.09 - 2017.06
        sub_title: Class 2 of the Yuanpei Project
        description: |

      - layout: left
        title: Peking University
        caption: 2017.09 - 2021.07
        sub_title: B.S. of Data Science and Big Data Technology, School of EECS
        # quote: >
        #   Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
#   During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

#   I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.
      # - layout: left
      #   title: Peking University
      #   caption: 2021.09 - now
      #   sub_title: M.S. of Computer Science and Technology
      #   description: |

  - title: Research
    layout: text
    content: |
      I'm advised by [Dr. Guojie Song](https://www.gjsong-pku.cn/).

      My research interests include graph machine learning and social computing.

      <mark>Publications</mark>

      - Guojie Song, Yizhou Zhang, **Lingjun Xu** and Haibing Lu. Domain Adaptive Network Embedding. IEEE Transactions on Big Data, 2020. [[link](https://ieeexplore.ieee.org/document/9241052)]
      - Qingqing Long, **Lingjun Xu**(Equal Contribution), Zheng Fang, and Guojie Song. HGK-GNN: Heterogeneous Graph Kernel based Graph Neural Networks. KDD, 2021. [[link](https://doi.org/10.1145/3447548.3467429)]

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      # - layout: top-middle
      #   title: Super awesome project
      #   link: github.com/sproogen
      #   # link_text: Project Website
      #   additional_links:
      #     - title:  sproogen/modern-resume-theme
      #       icon: fab fa-github
      #       url: github.com/sproogen/modern-resume-theme
      #     # - title:  Github page for project (eg. sproogen/modern-resume-theme)
      #     #   icon: fab fa-github
      #     #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
      #   quote: >
      #     This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
      #   description: | # this will include new lines to allow paragraphs
      #     I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Intern Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Tencent Map, Beijing
      #   link: boringcompany.com
      #   # link_text: boringcompany.com
        sub_title: Android Software Development Engineer Intern
        caption: 2020.07 - 2020.10
      #   quote: >
      #     Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
      #       Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Skills
    layout: list
    content:
      - title: Programming
        description: |
          - **Proficient:** Python(PyTorch), C/C++
          - **Intermediate:** Java
          - **Basic:** HTML, CSS, Javascript, Android
      - title: Languages
        description: |
          - **Native:** Cantonese & Mandarin
          - **Fluent:** English
          - **Basic:** Japanese, Korean, Italian

  - title: A Little More About Me
    layout: list
    content: # this will include new lines to allow paragraphs
      - title: Assumed Names
        description: |
          Sherria, Irena, Reikun, Ayako(綾子)
      - title: Hobbies
        description: |
          - **Music:** Piano & Vocal music [see [PKUEECS129](https://eecs129.site)]
          - **Sports:** Swimming & Tennis
          - **Writing Stories** [see Scarlet Rook(绯色的乌鸦) [blog](https://ScarletRook.github.io)]
          - **Studying Languages**
          - **History & Geography**
          - **Favorite Artists:** Shen Zhou, Yunlong Zheng, Ayanga, Mai Kuraki
          - **Favorite Tennis Players:** Roger Federer & Denis Shapovalov
          - **Favorite Manga:** Detective Conan

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]